

USE ROLE USERADMIN;
CREATE OR REPLACE ROLE ROLE_ACC_ADMIN;
USE ROLE ACCOUNTADMIN;

-- Grant CREATE INTEGRATION privilege to ROLE_ACC_ADMIN
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
use role securityadmin;
-- Grant MANAGE GRANTS to allow ROLE_ACC_ADMIN to assign roles
GRANT MANAGE GRANTS,create role ,create user ON ACCOUNT TO ROLE ROLE_ACC_ADMIN with Grant option;
GRANT USAGE ON DATABASE <Database name> TO ROLE ROLE_ACC_ADMIN;
GRANT USAGE ON SCHEMA <Database name>.<schema name> TO ROLE ROLE_ACC_ADMIN;
GRANT CREATE MASKING POLICY ON SCHEMA <Database name>.<schema name> TO ROLE ROLE_ACC_ADMIN;
GRANT CREATE TAG BASED MASKING POLICY ON SCHEMA <Database name>.<schema name> TO ROLE ROLE_ACC_ADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT APPLY AUTHENTICATION POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN WITH GRANT OPTION;
GRANT CREATE USER ON ACCOUNT TO ROLE ROLE_ACC_ADMIN WITH GRANT OPTION;
GRANT MONITOR ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;

GRANT CREATE NETWORK RULE ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT CREATE NETWORK POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT APPLY NETWORK POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT ROLE ROLE_ACC_ADMIN TO USER 'YOUR_USER'

GRANT CREATE PASSWORD POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT APPLY PASSWORD POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT CREATE SESSION POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT APPLY SESSION POLICY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;

GRANT MODIFY ON ACCOUNT TO ROLE ROLE_ACC_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ACC_ADMIN;
GRANT ROLE ROLE_ACC_ADMIN TO USER YOUR_USER;

-- Run as ACCOUNTADMIN (needed to create warehouse)
-- Switch back to SECURITYADMIN for grants
---------------------------------------------------------
-- 1. Create a dedicated role for GitHub deployments
---------------------------------------------------------

